apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: hello-gateway
  description: My Test Location
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=spring-cloud-gateway,app=hello-world'
spec:
  owner: dev-team-2
  lifecycle: alpha
  targets:
    - ./component-gateway.yaml
