apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-gateway
  description: Tanzu Spring Cloud Gateway
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=spring-cloud-gateway,app=hello-world'
spec:
  type: service
  lifecycle: alpha
  owner: dev-team-2
  system: hello-world