apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-template
  description: hello-template
  tags:
    - yaml
spec:
  type: service
  lifecycle: experimental
  owner: default-team
  providesApis:
    - agify-api